#!/bin/bash -l
#SBATCH --job-name="opti 3x3 fans Motus data"
#SBATCH --account="s929"
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --constraint=gpu
#SBATCH --partition=debug


python ./run-cmaes.py
